version: '3.7'

services:
  rtlsdr-airband:
    container_name: rtlsdr-airband
    restart: unless-stopped
    privileged: true
    volumes:
      - /opt/docker/rtlsdr-airband/config:/config
    image: ghcr.io/dan-r/rtlsdr-airband-docker:main
